STM8S/A Standard Peripherals Firmware Library: ADC2_ContinuousConversion
ADC2_ContinuousConversion
Functions
static void ADC_Config ()
Configure ADC2 Continuous Conversion with End Of Conversion interrupt enabled .
static void GPIO_Config (void)
Configure GPIO for LEDs and buttons available on the evaluation board.
void main (void)
ADC2_ContinuousConversion main entry point.
Variables
uint16_t Conversion_Value = 0
Function Documentation
static void ADC_Config () [static]
Configure ADC2 Continuous Conversion with End Of Conversion interrupt enabled .
Parameters:
None
Return values:
None
Definition at line 68 of file STM8S_StdPeriph_Examples/ADC2/ADC2_ContinuousConversion/main.c.
References ADC2_ALIGN_RIGHT, ADC2_CHANNEL_9, ADC2_CONVERSIONMODE_CONTINUOUS, ADC2_DeInit(), ADC2_EXTTRIG_TIM, ADC2_Init(), ADC2_ITConfig(), ADC2_PRESSEL_FCPU_D2, ADC2_SCHMITTTRIG_CHANNEL9, ADC2_StartConversion(), DISABLE, ENABLE, enableInterrupts, GPIO_Init(), GPIO_MODE_IN_FL_NO_IT, GPIO_PIN_6, and GPIOE.
Referenced by main().
static void GPIO_Config (void) [static]
Configure GPIO for LEDs and buttons available on the evaluation board.
Parameters:
None
Return values:
None
Definition at line 96 of file STM8S_StdPeriph_Examples/ADC2/ADC2_ContinuousConversion/main.c.
References LED1, LED2, LED3, LED4, and STM_EVAL_LEDInit().
Referenced by main().
void main (void)
ADC2_ContinuousConversion main entry point.
Main program.
Parameters:
None
Return values:
None
Definition at line 50 of file STM8S_StdPeriph_Examples/ADC2/ADC2_ContinuousConversion/main.c.
References ADC_Config(), and GPIO_Config().
Variable Documentation
uint16_t Conversion_Value = 0
Definition at line 39 of file STM8S_StdPeriph_Examples/ADC2/ADC2_ContinuousConversion/main.c.
For complete documentation on STM8 8-bit Microcontrollers platform visit www.st.com