STM8S/A Standard Peripherals Firmware Library: DataExchange
DataExchange
I2C_TwoBoards
Functions
TestStatus Buffercmp (uint8_t *pBuffer1, uint8_t *pBuffer2, uint16_t BufferLength)
Compares two buffers.
void main ()
Main program.
Variables
uint8_t HEADER_ADDRESS_Read = (((SLAVE_ADDRESS & 0xFF00) >> 7) | 0xF1)
uint8_t HEADER_ADDRESS_Write
uint8_t i = 0
__IO uint8_t NumByteToRead = BUFFERSIZE
__IO uint8_t NumOfBytes = BUFFERSIZE
__IO uint8_t Rx_Idx = 0
__IO uint8_t RxBuffer [BUFFERSIZE]
TestStatus TransferStatus1 = FAILED
__IO uint8_t Tx_Idx = 0
__IO uint8_t TxBuffer [BUFFERSIZE]
Function Documentation
TestStatus Buffercmp (uint8_t * pBuffer1, uint8_t * pBuffer2, uint16_t BufferLength)
Compares two buffers.
Parameters:
pBuffer1,pBuffer2,: buffers to be compared.
BufferLength,: buffer's length
Return values:
PASSED,: pBuffer1 identical to pBuffer2 FAILED: pBuffer1 differs from pBuffer2
void main (void)
Main program.
Parameters:
None
Return values:
None
Definition at line 64 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/main.c.
References Buffercmp(), BUFFERSIZE, CLK_HSIPrescalerConfig(), CLK_PRESCALER_HSIDIV1, CLK_PRESCALER_HSIDIV2, Delay(), disableInterrupts, ENABLE, enableInterrupts, FAILED, HEADER_ADDRESS_Read, HEADER_ADDRESS_Write, i, I2C_ACK_CURR, I2C_ACK_NONE, I2C_AcknowledgeConfig(), I2C_ADDMODE_7BIT, I2C_CheckEvent(), I2C_DIRECTION_RX, I2C_DIRECTION_TX, I2C_DUTYCYCLE_2, I2C_EVENT_MASTER_BYTE_RECEIVED, I2C_EVENT_MASTER_MODE_ADDRESS10, I2C_EVENT_MASTER_MODE_SELECT, I2C_EVENT_MASTER_RECEIVER_MODE_SELECTED, I2C_FLAG_BUSBUSY, I2C_FLAG_RXNOTEMPTY, I2C_FLAG_TRANSFERFINISHED, I2C_GenerateSTART(), I2C_GenerateSTOP(), I2C_GetFlagStatus(), I2C_Init(), I2C_IT_BUF, I2C_IT_EVT, I2C_ITConfig(), I2C_ReceiveData(), I2C_Send7bitAddress(), I2C_SendData(), I2C_SPEED, LED1, LED2, LED3, LED4, NumByteToRead, NumOfBytes, RESET, Rx_Idx, RxBuffer, SLAVE_ADDRESS, STM_EVAL_LEDInit(), STM_EVAL_LEDOff(), STM_EVAL_LEDToggle(), TransferStatus1, and TxBuffer.
Variable Documentation
uint8_t HEADER_ADDRESS_Read = (((SLAVE_ADDRESS & 0xFF00) >> 7) | 0xF1)
Referenced by main().
uint8_t HEADER_ADDRESS_Write
Referenced by INTERRUPT_HANDLER(), and main().
uint8_t i = 0
Definition at line 50 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/main.c.
Referenced by main(), SC_decode_Answer2reset(), SD_GetCIDRegister(), SD_GetCSDRegister(), SD_GetDataResponse(), SD_Init(), SD_ReadBlock(), SD_ReadBuffer(), SD_SendCmd(), SD_WriteBlock(), and SD_WriteBuffer().
__IO uint8_t NumByteToRead = BUFFERSIZE
Definition at line 48 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/main.c.
Referenced by main().
__IO uint8_t NumOfBytes = BUFFERSIZE
Definition at line 49 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/main.c.
Referenced by INTERRUPT_HANDLER(), and main().
__IO uint8_t Rx_Idx = 0
Definition at line 47 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/main.c.
Referenced by main().
__IO uint8_t RxBuffer[BUFFERSIZE]
Definition at line 51 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/main.c.
Referenced by main().
TestStatus TransferStatus1 = FAILED
Definition at line 52 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/main.c.
__IO uint8_t Tx_Idx = 0
Definition at line 47 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/main.c.
Referenced by INTERRUPT_HANDLER().
__IO uint8_t TxBuffer[BUFFERSIZE]
Definition at line 44 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
Referenced by INTERRUPT_HANDLER(), and main().
For complete documentation on STM8 8-bit Microcontrollers platform visit www.st.com