STM8S/A Standard Peripherals Firmware Library: FLASH_WriteWord
FLASH_WriteWord
Enumerations
enum TestStatus {
FAILED = 0, PASSED = !FAILED, FAILED = 0, PASSED = !FAILED,
FAILED = 0, PASSED = !FAILED, FAILED = 0, PASSED = !FAILED,
FAILED = 0, PASSED = !FAILED, FAILED = 0, PASSED = !FAILED,
FAILED = 0, PASSED = !FAILED, FAILED = 0, PASSED = !FAILED,
FAILED = 0, PASSED = !FAILED, FAILED = 0, PASSED = !FAILED
}
Functions
INTERRUPT_HANDLER (TLI_IRQHandler, 0)
Top Level Interrupt routine.
INTERRUPT_HANDLER (AWU_IRQHandler, 1)
Auto Wake Up Interrupt routine.
INTERRUPT_HANDLER (CLK_IRQHandler, 2)
Clock Controller Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTA_IRQHandler, 3)
External Interrupt PORTA Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTB_IRQHandler, 4)
External Interrupt PORTB Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTC_IRQHandler, 5)
External Interrupt PORTC Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTD_IRQHandler, 6)
External Interrupt PORTD Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTE_IRQHandler, 7)
External Interrupt PORTE Interrupt routine.
INTERRUPT_HANDLER (SPI_IRQHandler, 10)
SPI Interrupt routine.
INTERRUPT_HANDLER (TIM1_UPD_OVF_TRG_BRK_IRQHandler, 11)
Timer1 Update/Overflow/Trigger/Break Interrupt routine.
INTERRUPT_HANDLER (TIM1_CAP_COM_IRQHandler, 12)
Timer1 Capture/Compare Interrupt routine.
INTERRUPT_HANDLER (TIM2_UPD_OVF_BRK_IRQHandler, 13)
Timer2 Update/Overflow/Break Interrupt routine.
INTERRUPT_HANDLER (TIM2_CAP_COM_IRQHandler, 14)
Timer2 Capture/Compare Interrupt routine.
INTERRUPT_HANDLER (I2C_IRQHandler, 19)
I2C Interrupt routine.
INTERRUPT_HANDLER (ADC1_IRQHandler, 22)
ADC1 interrupt routine.
INTERRUPT_HANDLER (TIM4_UPD_OVF_IRQHandler, 23)
Timer4 Update/Overflow Interrupt routine.
INTERRUPT_HANDLER (EEPROM_EEC_IRQHandler, 24)
Eeprom EEC Interrupt routine.
INTERRUPT_HANDLER_TRAP (TRAP_IRQHandler)
TRAP interrupt routine.
void main (void)
How to Write a word & Erase Byte on Data EEPROM memory.
Variables
__IO TestStatus OperationStatus = FAILED
Enumeration Type Documentation
enum TestStatus
Enumerator:
FAILED
PASSED
FAILED
PASSED
FAILED
PASSED
FAILED
PASSED
FAILED
PASSED
FAILED
PASSED
FAILED
PASSED
FAILED
PASSED
FAILED
PASSED
FAILED
PASSED
Definition at line 37 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/main.c.
Function Documentation
INTERRUPT_HANDLER (TLI_IRQHandler , 0)
Top Level Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 88 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/stm8s_it.c.
INTERRUPT_HANDLER (AWU_IRQHandler , 1)
Auto Wake Up Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 101 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/stm8s_it.c.
INTERRUPT_HANDLER (CLK_IRQHandler , 2)
Clock Controller Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 114 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTA_IRQHandler , 3)
External Interrupt PORTA Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 127 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTB_IRQHandler , 4)
External Interrupt PORTB Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 139 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTC_IRQHandler , 5)
External Interrupt PORTC Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 152 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTD_IRQHandler , 6)
External Interrupt PORTD Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 165 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTE_IRQHandler , 7)
External Interrupt PORTE Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 178 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/stm8s_it.c.
INTERRUPT_HANDLER (SPI_IRQHandler , 10)
SPI Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 233 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/stm8s_it.c.
INTERRUPT_HANDLER (TIM1_UPD_OVF_TRG_BRK_IRQHandler , 11)
Timer1 Update/Overflow/Trigger/Break Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 246 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/stm8s_it.c.
INTERRUPT_HANDLER (TIM1_CAP_COM_IRQHandler , 12)
Timer1 Capture/Compare Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 259 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/stm8s_it.c.
INTERRUPT_HANDLER (TIM2_UPD_OVF_BRK_IRQHandler , 13)
Timer2 Update/Overflow/Break Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 299 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/stm8s_it.c.
INTERRUPT_HANDLER (TIM2_CAP_COM_IRQHandler , 14)
Timer2 Capture/Compare Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 312 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/stm8s_it.c.
INTERRUPT_HANDLER (I2C_IRQHandler , 19)
I2C Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 384 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/stm8s_it.c.
INTERRUPT_HANDLER (ADC1_IRQHandler , 22)
ADC1 interrupt routine.
Parameters:
None
Return values:
None
Definition at line 466 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/stm8s_it.c.
INTERRUPT_HANDLER (TIM4_UPD_OVF_IRQHandler , 23)
Timer4 Update/Overflow Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 494 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/stm8s_it.c.
INTERRUPT_HANDLER (EEPROM_EEC_IRQHandler , 24)
Eeprom EEC Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 508 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/stm8s_it.c.
INTERRUPT_HANDLER_TRAP (TRAP_IRQHandler)
TRAP interrupt routine.
Parameters:
None
Return values:
None
Definition at line 74 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/stm8s_it.c.
void main (void)
How to Write a word & Erase Byte on Data EEPROM memory.
Examples description
Program a word at address 0x4100
Check program using Read byte
Erase word using erase byte
Check the 4 bytes (word) value is 0x00.
Parameters:
None
Return values:
None
Definition at line 56 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/main.c.
References BYTE_0, BYTE_1, BYTE_2, BYTE_3, FAILED, FLASH_EraseByte(), FLASH_MEMTYPE_DATA, FLASH_PROGRAMTIME_STANDARD, FLASH_ProgramWord(), FLASH_ReadByte(), FLASH_SetProgrammingTime(), FLASH_Unlock(), OperationStatus, and PASSED.
Variable Documentation
__IO TestStatus OperationStatus = FAILED
Definition at line 41 of file STM8S_StdPeriph_Examples/FLASH/FLASH_WriteWordOperation/main.c.
For complete documentation on STM8 8-bit Microcontrollers platform visit www.st.com