STM8S/A Standard Peripherals Firmware Library: I2C_DataExchange
I2C_DataExchange
I2C_TwoBoards
Functions
INTERRUPT_HANDLER (TLI_IRQHandler, 0)
Top Level Interrupt routine.
INTERRUPT_HANDLER (AWU_IRQHandler, 1)
Auto Wake Up Interrupt routine.
INTERRUPT_HANDLER (CLK_IRQHandler, 2)
Clock Controller Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTA_IRQHandler, 3)
External Interrupt PORTA Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTB_IRQHandler, 4)
External Interrupt PORTB Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTC_IRQHandler, 5)
External Interrupt PORTC Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTD_IRQHandler, 6)
External Interrupt PORTD Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTE_IRQHandler, 7)
External Interrupt PORTE Interrupt routine.
INTERRUPT_HANDLER (SPI_IRQHandler, 10)
SPI Interrupt routine.
INTERRUPT_HANDLER (TIM1_UPD_OVF_TRG_BRK_IRQHandler, 11)
Timer1 Update/Overflow/Trigger/Break Interrupt routine.
INTERRUPT_HANDLER (TIM1_CAP_COM_IRQHandler, 12)
Timer1 Capture/Compare Interrupt routine.
INTERRUPT_HANDLER (TIM2_UPD_OVF_BRK_IRQHandler, 13)
Timer2 Update/Overflow/Break Interrupt routine.
INTERRUPT_HANDLER (TIM2_CAP_COM_IRQHandler, 14)
Timer2 Capture/Compare Interrupt routine.
INTERRUPT_HANDLER (I2C_IRQHandler, 19)
I2C Interrupt routine.
INTERRUPT_HANDLER (ADC1_IRQHandler, 22)
ADC1 interrupt routine.
INTERRUPT_HANDLER (TIM4_UPD_OVF_IRQHandler, 23)
Timer4 Update/Overflow Interrupt routine.
INTERRUPT_HANDLER (EEPROM_EEC_IRQHandler, 24)
Eeprom EEC Interrupt routine.
INTERRUPT_HANDLER_TRAP (TRAP_IRQHandler)
TRAP interrupt routine.
void main (void)
Main program.
Variables
__IO uint16_t Event = 0x00
uint8_t HEADER_ADDRESS_Read
uint8_t HEADER_ADDRESS_Write = (((SLAVE_ADDRESS & 0xFF00) >> 7) | 0xF0)
__IO uint8_t NumOfBytes
__IO uint8_t Rx_Idx = 0
__IO uint8_t Slave_Buffer_Rx [255]
__IO uint8_t Tx_Idx = 0
__IO uint8_t Tx_Idx
__IO uint8_t TxBuffer [BUFFERSIZE]
Function Documentation
INTERRUPT_HANDLER (TLI_IRQHandler , 0)
Top Level Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 96 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
INTERRUPT_HANDLER (AWU_IRQHandler , 1)
Auto Wake Up Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 109 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
INTERRUPT_HANDLER (CLK_IRQHandler , 2)
Clock Controller Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 122 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTA_IRQHandler , 3)
External Interrupt PORTA Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 135 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTB_IRQHandler , 4)
External Interrupt PORTB Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 147 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTC_IRQHandler , 5)
External Interrupt PORTC Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 160 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTD_IRQHandler , 6)
External Interrupt PORTD Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 173 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTE_IRQHandler , 7)
External Interrupt PORTE Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 186 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
INTERRUPT_HANDLER (SPI_IRQHandler , 10)
SPI Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 241 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
INTERRUPT_HANDLER (TIM1_UPD_OVF_TRG_BRK_IRQHandler , 11)
Timer1 Update/Overflow/Trigger/Break Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 254 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
INTERRUPT_HANDLER (TIM1_CAP_COM_IRQHandler , 12)
Timer1 Capture/Compare Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 267 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
INTERRUPT_HANDLER (TIM2_UPD_OVF_BRK_IRQHandler , 13)
Timer2 Update/Overflow/Break Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 307 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
INTERRUPT_HANDLER (TIM2_CAP_COM_IRQHandler , 14)
Timer2 Capture/Compare Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 320 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
INTERRUPT_HANDLER (I2C_IRQHandler , 19)
I2C Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 392 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
References DISABLE, ENABLE, HEADER_ADDRESS_Write, I2C_DIRECTION_TX, I2C_EVENT_MASTER_BYTE_TRANSMITTED, I2C_EVENT_MASTER_BYTE_TRANSMITTING, I2C_EVENT_MASTER_MODE_ADDRESS10, I2C_EVENT_MASTER_MODE_SELECT, I2C_EVENT_MASTER_TRANSMITTER_MODE_SELECTED, I2C_GenerateSTOP(), I2C_GetLastEvent(), I2C_IT_BUF, I2C_IT_EVT, I2C_ITConfig(), I2C_Send7bitAddress(), I2C_SendData(), NumOfBytes, SLAVE_ADDRESS, Tx_Idx, and TxBuffer.
INTERRUPT_HANDLER (ADC1_IRQHandler , 22)
ADC1 interrupt routine.
Parameters:
None
Return values:
None
Definition at line 532 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
INTERRUPT_HANDLER (TIM4_UPD_OVF_IRQHandler , 23)
Timer4 Update/Overflow Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 560 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
INTERRUPT_HANDLER (EEPROM_EEC_IRQHandler , 24)
Eeprom EEC Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 574 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
INTERRUPT_HANDLER_TRAP (TRAP_IRQHandler)
TRAP interrupt routine.
Parameters:
None
Return values:
None
Definition at line 82 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
void main (void)
Main program.
Parameters:
None
Return values:
None
Definition at line 54 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Slave/main.c.
References CLK_HSIPrescalerConfig(), CLK_PRESCALER_HSIDIV1, ENABLE, enableInterrupts, I2C_ACK_CURR, I2C_ADDMODE_10BIT, I2C_ADDMODE_7BIT, I2C_DeInit(), I2C_DUTYCYCLE_2, I2C_Init(), I2C_IT_BUF, I2C_IT_ERR, I2C_IT_EVT, I2C_ITConfig(), LED2, SLAVE_ADDRESS, STM_EVAL_LEDInit(), and STM_EVAL_LEDOff().
Variable Documentation
__IO uint16_t Event = 0x00
Definition at line 45 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Slave/stm8s_it.c.
uint8_t HEADER_ADDRESS_Read
uint8_t HEADER_ADDRESS_Write = (((SLAVE_ADDRESS & 0xFF00) >> 7) | 0xF0)
__IO uint8_t NumOfBytes
Definition at line 49 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/main.c.
Referenced by INTERRUPT_HANDLER(), and main().
__IO uint8_t Rx_Idx = 0
Definition at line 44 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Slave/stm8s_it.c.
__IO uint8_t Slave_Buffer_Rx[255]
Definition at line 43 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Slave/stm8s_it.c.
__IO uint8_t Tx_Idx = 0
Definition at line 44 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Slave/stm8s_it.c.
__IO uint8_t Tx_Idx
Definition at line 47 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/main.c.
Referenced by INTERRUPT_HANDLER().
__IO uint8_t TxBuffer[BUFFERSIZE]
Definition at line 44 of file STM8S_StdPeriph_Examples/I2C/I2C_TwoBoards/I2C_DataExchange/Master/stm8s_it.c.
For complete documentation on STM8 8-bit Microcontrollers platform visit www.st.com