STM8S/A Standard Peripherals Firmware Library: EXTI_Exported_Functions
EXTI_Exported_Functions
Functions
void EXTI_DeInit (void)
Deinitializes the external interrupt control registers to their default reset value.
EXTI_Sensitivity_TypeDef EXTI_GetExtIntSensitivity (EXTI_Port_TypeDef Port)
Get the external interrupt sensitivity of the selected port.
EXTI_TLISensitivity_TypeDef EXTI_GetTLISensitivity (void)
Get the TLI interrupt sensitivity.
void EXTI_SetExtIntSensitivity (EXTI_Port_TypeDef Port, EXTI_Sensitivity_TypeDef SensitivityValue)
Set the external interrupt sensitivity of the selected port.
void EXTI_SetTLISensitivity (EXTI_TLISensitivity_TypeDef SensitivityValue)
Set the TLI interrupt sensitivity.
Function Documentation
void EXTI_DeInit (void)
Deinitializes the external interrupt control registers to their default reset value.
Parameters:
None
Return values:
None
Definition at line 53 of file stm8s_exti.c.
References EXTI, EXTI_CR1_RESET_VALUE, and EXTI_CR2_RESET_VALUE.
EXTI_Sensitivity_TypeDef EXTI_GetExtIntSensitivity (EXTI_Port_TypeDef Port)
Get the external interrupt sensitivity of the selected port.
Parameters:
Port The port number to access.
Return values:
EXTI_Sensitivity_TypeDef The external interrupt sensitivity of the selected port.
Definition at line 126 of file stm8s_exti.c.
References assert_param, EXTI, EXTI_CR1_PAIS, EXTI_CR1_PBIS, EXTI_CR1_PCIS, EXTI_CR1_PDIS, EXTI_CR2_PEIS, EXTI_PORT_GPIOA, EXTI_PORT_GPIOB, EXTI_PORT_GPIOC, EXTI_PORT_GPIOD, EXTI_PORT_GPIOE, and IS_EXTI_PORT_OK.
EXTI_TLISensitivity_TypeDef EXTI_GetTLISensitivity (void)
Get the TLI interrupt sensitivity.
Parameters:
None
Return values:
EXTI_TLISensitivity_TypeDef The TLI interrupt sensitivity read.
Definition at line 162 of file stm8s_exti.c.
References EXTI, and EXTI_CR2_TLIS.
void EXTI_SetExtIntSensitivity (EXTI_Port_TypeDef Port, EXTI_Sensitivity_TypeDef SensitivityValue)
Set the external interrupt sensitivity of the selected port.
Warning:
The modification of external interrupt sensitivity is only possible when the interrupts are disabled.
The normal behavior is to disable the interrupts before calling this function, and re-enable them after.
Parameters:
Port The port number to access.
SensitivityValue The external interrupt sensitivity value to set.
Return values:
None
Required preconditions:
Global interrupts must be disabled before calling this function.
Definition at line 70 of file stm8s_exti.c.
References assert_param, EXTI, EXTI_CR1_PAIS, EXTI_CR1_PBIS, EXTI_CR1_PCIS, EXTI_CR1_PDIS, EXTI_CR2_PEIS, EXTI_PORT_GPIOA, EXTI_PORT_GPIOB, EXTI_PORT_GPIOC, EXTI_PORT_GPIOD, EXTI_PORT_GPIOE, IS_EXTI_PORT_OK, and IS_EXTI_SENSITIVITY_OK.
Referenced by main(), and STM_EVAL_PBInit().
void EXTI_SetTLISensitivity (EXTI_TLISensitivity_TypeDef SensitivityValue)
Set the TLI interrupt sensitivity.
Parameters:
SensitivityValue The TLI interrupt sensitivity value.
Return values:
None
Required preconditions:
Global interrupts must be disabled before calling this function.
Definition at line 111 of file stm8s_exti.c.
References assert_param, EXTI, EXTI_CR2_TLIS, and IS_EXTI_TLISENSITIVITY_OK.
Referenced by main().
For complete documentation on STM8 8-bit Microcontrollers platform visit www.st.com