STM8S/A Standard Peripherals Firmware Library: WWDG_Exported_Functions
WWDG_Exported_Functions
STM8S_StdPeriph_Driver
Functions
uint8_t WWDG_GetCounter (void)
Gets the WWDG Counter Value.
void WWDG_Init (uint8_t Counter, uint8_t WindowValue)
Initializes the WWDG peripheral.
void WWDG_SetCounter (uint8_t Counter)
Refreshes the WWDG peripheral.
void WWDG_SetWindowValue (uint8_t WindowValue)
Sets the WWDG window value.
void WWDG_SWReset (void)
Generates immediate WWDG RESET.
Function Documentation
uint8_t WWDG_GetCounter (void)
Gets the WWDG Counter Value.
This value could be used to check if WWDG is in the window, where refresh is allowed.
Parameters:
None
Return values:
WWDG Counter Value
Definition at line 86 of file stm8s_wwdg.c.
References WWDG.
Referenced by main().
void WWDG_Init (uint8_t Counter, uint8_t WindowValue)
Initializes the WWDG peripheral.
This function set Window Register = WindowValue, Counter Register according to Counter and ENABLE WWDG
Parameters:
Counter : WWDG counter value
WindowValue : specifies the WWDG Window Register, range is 0x00 to 0x7F.
Return values:
None
Definition at line 53 of file stm8s_wwdg.c.
References assert_param, Counter, IS_WWDG_WINDOWLIMITVALUE_OK, WWDG, WWDG_CR_T6, WWDG_CR_WDGA, and WWDG_WR_RESET_VALUE.
Referenced by WWDG_Config().
void WWDG_SetCounter (uint8_t Counter)
Refreshes the WWDG peripheral.
Parameters:
Counter : WWDG Counter Value This parameter must be a number between 0x40 and 0x7F.
Return values:
None
Definition at line 69 of file stm8s_wwdg.c.
References assert_param, BIT_MASK, IS_WWDG_COUNTERVALUE_OK, and WWDG.
Referenced by main().
void WWDG_SetWindowValue (uint8_t WindowValue)
Sets the WWDG window value.
Parameters:
WindowValue,: specifies the window value to be compared to the downcounter. This parameter value must be lower than 0x80.
Return values:
None
Definition at line 108 of file stm8s_wwdg.c.
References assert_param, IS_WWDG_WINDOWLIMITVALUE_OK, WWDG, WWDG_CR_T6, and WWDG_CR_WDGA.
void WWDG_SWReset (void)
Generates immediate WWDG RESET.
Parameters:
None
Return values:
None
Definition at line 96 of file stm8s_wwdg.c.
References WWDG, and WWDG_CR_WDGA.
For complete documentation on STM8 8-bit Microcontrollers platform visit www.st.com