STM8S/A Standard Peripherals Firmware Library: TIM1_6Steps
TIM1_6Steps
Functions
INTERRUPT_HANDLER (TLI_IRQHandler, 0)
Top Level Interrupt routine.
INTERRUPT_HANDLER (AWU_IRQHandler, 1)
Auto Wake Up Interrupt routine.
INTERRUPT_HANDLER (CLK_IRQHandler, 2)
Clock Controller Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTA_IRQHandler, 3)
External Interrupt PORTA Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTB_IRQHandler, 4)
External Interrupt PORTB Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTC_IRQHandler, 5)
External Interrupt PORTC Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTD_IRQHandler, 6)
External Interrupt PORTD Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTE_IRQHandler, 7)
External Interrupt PORTE Interrupt routine.
INTERRUPT_HANDLER (SPI_IRQHandler, 10)
SPI Interrupt routine.
INTERRUPT_HANDLER (TIM1_UPD_OVF_TRG_BRK_IRQHandler, 11)
Timer1 Update/Overflow/Trigger/Break Interrupt routine.
INTERRUPT_HANDLER (TIM1_CAP_COM_IRQHandler, 12)
Timer1 Capture/Compare Interrupt routine.
INTERRUPT_HANDLER (TIM2_UPD_OVF_BRK_IRQHandler, 13)
Timer2 Update/Overflow/Break Interrupt routine.
INTERRUPT_HANDLER (TIM2_CAP_COM_IRQHandler, 14)
Timer2 Capture/Compare Interrupt routine.
INTERRUPT_HANDLER (I2C_IRQHandler, 19)
I2C Interrupt routine.
INTERRUPT_HANDLER (ADC1_IRQHandler, 22)
ADC1 interrupt routine.
INTERRUPT_HANDLER (TIM4_UPD_OVF_IRQHandler, 23)
Timer4 Update/Overflow Interrupt routine.
INTERRUPT_HANDLER (EEPROM_EEC_IRQHandler, 24)
Eeprom EEC Interrupt routine.
INTERRUPT_HANDLER_TRAP (TRAP_IRQHandler)
TRAP interrupt routine.
void main (void)
Main program.
static void TIM1_Config (void)
Configure TIM1 to generate 6 Steps PWM signal.
static void TIM4_Config (void)
Configure TIM4 to generate a software COM event each 180 ms.
Function Documentation
INTERRUPT_HANDLER (TLI_IRQHandler , 0)
Top Level Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 76 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/stm8s_it.c.
INTERRUPT_HANDLER (AWU_IRQHandler , 1)
Auto Wake Up Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 88 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/stm8s_it.c.
INTERRUPT_HANDLER (CLK_IRQHandler , 2)
Clock Controller Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 100 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTA_IRQHandler , 3)
External Interrupt PORTA Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 112 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTB_IRQHandler , 4)
External Interrupt PORTB Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 124 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTC_IRQHandler , 5)
External Interrupt PORTC Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 136 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTD_IRQHandler , 6)
External Interrupt PORTD Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 148 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTE_IRQHandler , 7)
External Interrupt PORTE Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 160 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/stm8s_it.c.
INTERRUPT_HANDLER (SPI_IRQHandler , 10)
SPI Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 211 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/stm8s_it.c.
INTERRUPT_HANDLER (TIM1_UPD_OVF_TRG_BRK_IRQHandler , 11)
Timer1 Update/Overflow/Trigger/Break Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 223 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/stm8s_it.c.
INTERRUPT_HANDLER (TIM1_CAP_COM_IRQHandler , 12)
Timer1 Capture/Compare Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 235 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/stm8s_it.c.
References DISABLE, ENABLE, step, TIM1_CCxCmd(), TIM1_CCxNCmd(), TIM1_CHANNEL_1, TIM1_CHANNEL_2, TIM1_CHANNEL_3, TIM1_ClearITPendingBit(), TIM1_FORCEDACTION_ACTIVE, TIM1_FORCEDACTION_INACTIVE, TIM1_IT_COM, and TIM1_SelectOCxM().
INTERRUPT_HANDLER (TIM2_UPD_OVF_BRK_IRQHandler , 13)
Timer2 Update/Overflow/Break Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 380 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/stm8s_it.c.
INTERRUPT_HANDLER (TIM2_CAP_COM_IRQHandler , 14)
Timer2 Capture/Compare Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 392 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/stm8s_it.c.
INTERRUPT_HANDLER (I2C_IRQHandler , 19)
I2C Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 459 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/stm8s_it.c.
INTERRUPT_HANDLER (ADC1_IRQHandler , 22)
ADC1 interrupt routine.
Parameters:
None
Return values:
None
Definition at line 539 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/stm8s_it.c.
INTERRUPT_HANDLER (TIM4_UPD_OVF_IRQHandler , 23)
Timer4 Update/Overflow Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 568 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/stm8s_it.c.
References TIM1_EVENTSOURCE_COM, TIM1_GenerateEvent(), TIM4_ClearITPendingBit(), TIM4_IT_UPDATE, and TimeCounter.
INTERRUPT_HANDLER (EEPROM_EEC_IRQHandler , 24)
Eeprom EEC Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 595 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/stm8s_it.c.
INTERRUPT_HANDLER_TRAP (TRAP_IRQHandler)
TRAP interrupt routine.
Parameters:
None
Return values:
None
Definition at line 65 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/stm8s_it.c.
void main (void)
Main program.
Parameters:
None
Return values:
None
Definition at line 51 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/main.c.
References ENABLE, enableInterrupts, TIM1_Config(), TIM1_CtrlPWMOutputs(), and TIM4_Config().
static void TIM1_Config (void) [static]
Configure TIM1 to generate 6 Steps PWM signal.
Parameters:
None
Return values:
None
Definition at line 73 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/main.c.
References ENABLE, TIM1_AUTOMATICOUTPUT_ENABLE, TIM1_BDTRConfig(), TIM1_BREAK_DISABLE, TIM1_BREAKPOLARITY_LOW, TIM1_CCPreloadControl(), TIM1_Cmd(), TIM1_COUNTERMODE_UP, TIM1_DeInit(), TIM1_IT_COM, TIM1_ITConfig(), TIM1_LOCKLEVEL_OFF, TIM1_OC1Init(), TIM1_OC2Init(), TIM1_OC3Init(), TIM1_OCIDLESTATE_SET, TIM1_OCMODE_TIMING, TIM1_OCNIDLESTATE_SET, TIM1_OCNPOLARITY_HIGH, TIM1_OCPOLARITY_HIGH, TIM1_OSSISTATE_ENABLE, TIM1_OUTPUTNSTATE_ENABLE, TIM1_OUTPUTSTATE_ENABLE, and TIM1_TimeBaseInit().
Referenced by main().
static void TIM4_Config (void) [static]
Configure TIM4 to generate a software COM event each 180 ms.
Parameters:
None
Return values:
None
Definition at line 113 of file STM8S_StdPeriph_Examples/TIM1/TIM1_6Steps/main.c.
References ENABLE, TIM4_Cmd(), TIM4_IT_UPDATE, TIM4_ITConfig(), TIM4_PRESCALER_128, and TIM4_TimeBaseInit().
Referenced by main().
For complete documentation on STM8 8-bit Microcontrollers platform visit www.st.com