STM8S/A Standard Peripherals Firmware Library: ITC_Exported_Functions
ITC_Exported_Functions
Functions
void ITC_DeInit (void)
Deinitializes the ITC registers to their default reset value.
uint8_t ITC_GetCPUCC (void)
Utility function used to read CC register.
uint8_t ITC_GetSoftIntStatus (void)
Gets the interrupt software priority bits (I1, I0) value from CPU CC register.
ITC_PriorityLevel_TypeDef ITC_GetSoftwarePriority (ITC_Irq_TypeDef IrqNum)
Gets the software priority of the specified interrupt source.
void ITC_SetSoftwarePriority (ITC_Irq_TypeDef IrqNum, ITC_PriorityLevel_TypeDef PriorityValue)
Sets the software priority of the specified interrupt source.
Function Documentation
void ITC_DeInit (void)
Deinitializes the ITC registers to their default reset value.
Parameters:
None
Return values:
None
Definition at line 80 of file stm8s_itc.c.
References ITC, and ITC_SPRX_RESET_VALUE.
uint8_t ITC_GetCPUCC (void)
Utility function used to read CC register.
Parameters:
None
Return values:
CPU CC register value
Definition at line 50 of file stm8s_itc.c.
Referenced by ITC_GetSoftIntStatus().
uint8_t ITC_GetSoftIntStatus (void)
Gets the interrupt software priority bits (I1, I0) value from CPU CC register.
Parameters:
None
Return values:
The interrupt software priority bits value.
Definition at line 97 of file stm8s_itc.c.
References CPU_CC_I1I0, and ITC_GetCPUCC().
ITC_PriorityLevel_TypeDef ITC_GetSoftwarePriority (ITC_Irq_TypeDef IrqNum)
Gets the software priority of the specified interrupt source.
Parameters:
IrqNum : Specifies the peripheral interrupt source.
Return values:
ITC_PriorityLevel_TypeDef : Specifies the software priority of the interrupt source.
Definition at line 107 of file stm8s_itc.c.
References assert_param, IS_ITC_IRQ_OK, ITC, ITC_IRQ_AWU, ITC_IRQ_CLK, ITC_IRQ_EEPROM_EEC, ITC_IRQ_I2C, ITC_IRQ_PORTA, ITC_IRQ_PORTB, ITC_IRQ_PORTC, ITC_IRQ_PORTD, ITC_IRQ_PORTE, ITC_IRQ_SPI, ITC_IRQ_TIM1_CAPCOM, ITC_IRQ_TIM1_OVF, ITC_IRQ_TIM2_CAPCOM, ITC_IRQ_TIM2_OVF, ITC_IRQ_TIM3_CAPCOM, ITC_IRQ_TIM3_OVF, ITC_IRQ_TIM4_OVF, and ITC_IRQ_TLI.
void ITC_SetSoftwarePriority (ITC_Irq_TypeDef IrqNum, ITC_PriorityLevel_TypeDef PriorityValue)
Sets the software priority of the specified interrupt source.
Note:
- The modification of the software priority is only possible when the interrupts are disabled.
The normal behavior is to disable the interrupt before calling this function, and re-enable it after.
The priority level 0 cannot be set (see product specification for more details).
Parameters:
IrqNum : Specifies the peripheral interrupt source.
PriorityValue : Specifies the software priority value to set, can be a value of ITC_PriorityLevel_TypeDef .
Return values:
None
Definition at line 220 of file stm8s_itc.c.
References assert_param, IS_ITC_INTERRUPTS_DISABLED, IS_ITC_IRQ_OK, IS_ITC_PRIORITY_OK, ITC, ITC_IRQ_AWU, ITC_IRQ_CLK, ITC_IRQ_EEPROM_EEC, ITC_IRQ_I2C, ITC_IRQ_PORTA, ITC_IRQ_PORTB, ITC_IRQ_PORTC, ITC_IRQ_PORTD, ITC_IRQ_PORTE, ITC_IRQ_SPI, ITC_IRQ_TIM1_CAPCOM, ITC_IRQ_TIM1_OVF, ITC_IRQ_TIM2_CAPCOM, ITC_IRQ_TIM2_OVF, ITC_IRQ_TIM3_CAPCOM, ITC_IRQ_TIM3_OVF, ITC_IRQ_TIM4_OVF, and ITC_IRQ_TLI.
Referenced by ITC_Config().
For complete documentation on STM8 8-bit Microcontrollers platform visit www.st.com