STM8S/A Standard Peripherals Firmware Library: UART1_MultiProcessor
UART1_MultiProcessor
Functions
void Delay (uint32_t nCount)
Delay.
static void GPIO_Config (void)
Configure GPIO for Leds and buttons available on the evaluation board.
void main (void)
Main program.
static void UART_Config (void)
UART1 and UART3 Configuration for multi processor communication.
Function Documentation
void Delay (uint32_t nCount)
Delay.
Parameters:
nCount
Return values:
None
static void GPIO_Config (void) [static]
Configure GPIO for Leds and buttons available on the evaluation board.
Parameters:
None
Return values:
None
void main (void)
Main program.
Parameters:
None
Return values:
None
Definition at line 51 of file STM8S_StdPeriph_Examples/UART1/UART1_MultiProcessor/main.c.
References Delay(), GPIO_Config(), LED1, LED2, LED3, LED4, RESET, STM_EVAL_LEDToggle(), UART1_FLAG_TXE, UART1_GetFlagStatus(), UART1_SendData9(), UART3_FLAG_RXNE, UART3_GetFlagStatus(), UART3_ReceiveData9(), and UART_Config().
static void UART_Config (void) [static]
UART1 and UART3 Configuration for multi processor communication.
Parameters:
None
Return values:
None
Definition at line 115 of file STM8S_StdPeriph_Examples/UART1/UART1_MultiProcessor/main.c.
References UART1_DeInit(), UART1_Init(), UART1_MODE_TXRX_ENABLE, UART1_PARITY_NO, UART1_SetAddress(), UART1_STOPBITS_1, UART1_SYNCMODE_CLOCK_DISABLE, UART1_WORDLENGTH_9D, UART3_DeInit(), UART3_Init(), UART3_MODE_TXRX_ENABLE, UART3_PARITY_NO, UART3_SetAddress(), UART3_STOPBITS_1, UART3_WAKEUP_ADDRESSMARK, UART3_WakeUpConfig(), and UART3_WORDLENGTH_9D.
Referenced by main().
For complete documentation on STM8 8-bit Microcontrollers platform visit www.st.com