STM8S/A Standard Peripherals Firmware Library: UART1_Interrupt
UART1_Interrupt
Enumerations
enum TestStatus {
FAILED = 0, PASSED = !FAILED, FAILED = 0, PASSED = !FAILED,
FAILED = 0, PASSED = !FAILED, FAILED = 0, PASSED = !FAILED,
FAILED = 0, PASSED = !FAILED, FAILED = 0, PASSED = !FAILED,
FAILED = 0, PASSED = !FAILED, FAILED = 0, PASSED = !FAILED,
FAILED = 0, PASSED = !FAILED, FAILED = 0, PASSED = !FAILED
}
Functions
TestStatus Buffercmp (uint8_t *pBuffer1, uint8_t *pBuffer2, uint16_t BufferLength)
Compares two buffers.
static void CLK_Config (void)
Configure system clock to run at 16Mhz.
void Delay (uint16_t nCount)
Delay.
uint8_t GetVar_NbrOfDataToRead1 (void)
Returns NbrOfDataToRead1 value.
uint8_t GetVar_NbrOfDataToRead2 (void)
Returns NbrOfDataToRead2 value.
uint8_t GetVar_NbrOfDataToTransfer1 (void)
Returns NbrOfDataToTransfer1 value.
uint8_t GetVar_NbrOfDataToTransfer2 (void)
Returns NbrOfDataToTransfer2 value.
uint8_t GetVar_RxCounter1 (void)
Returns RxCounter1 value.
uint8_t GetVar_RxCounter2 (void)
Returns RxCounter2 value.
uint8_t GetVar_TxCounter1 (void)
Returns TxCounter1 value.
uint8_t GetVar_TxCounter2 (void)
Returns TxCounter2 value.
uint8_t IncrementVar_RxCounter1 (void)
Increments RxCounter1 variable and return its value.
uint8_t IncrementVar_RxCounter2 (void)
Increments RxCounter2 variable and return its value.
uint8_t IncrementVar_TxCounter1 (void)
Increments TxCounter1 variable and return its value.
uint8_t IncrementVar_TxCounter2 (void)
Increments TxCounter2 variable and return its value.
INTERRUPT_HANDLER (TLI_IRQHandler, 0)
Top Level Interrupt routine.
INTERRUPT_HANDLER (AWU_IRQHandler, 1)
Auto Wake Up Interrupt routine.
INTERRUPT_HANDLER (CLK_IRQHandler, 2)
Clock Controller Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTA_IRQHandler, 3)
External Interrupt PORTA Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTB_IRQHandler, 4)
External Interrupt PORTB Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTC_IRQHandler, 5)
External Interrupt PORTC Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTD_IRQHandler, 6)
External Interrupt PORTD Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTE_IRQHandler, 7)
External Interrupt PORTE Interrupt routine.
INTERRUPT_HANDLER (SPI_IRQHandler, 10)
SPI Interrupt routine.
INTERRUPT_HANDLER (TIM1_UPD_OVF_TRG_BRK_IRQHandler, 11)
Timer1 Update/Overflow/Trigger/Break Interrupt routine.
INTERRUPT_HANDLER (TIM1_CAP_COM_IRQHandler, 12)
Timer1 Capture/Compare Interrupt routine.
INTERRUPT_HANDLER (TIM2_UPD_OVF_BRK_IRQHandler, 13)
Timer2 Update/Overflow/Break Interrupt routine.
INTERRUPT_HANDLER (TIM2_CAP_COM_IRQHandler, 14)
Timer2 Capture/Compare Interrupt routine.
INTERRUPT_HANDLER (I2C_IRQHandler, 19)
I2C Interrupt routine.
INTERRUPT_HANDLER (ADC1_IRQHandler, 22)
ADC1 interrupt routine.
INTERRUPT_HANDLER (TIM4_UPD_OVF_IRQHandler, 23)
Timer4 Update/Overflow Interrupt routine.
INTERRUPT_HANDLER (EEPROM_EEC_IRQHandler, 24)
Eeprom EEC Interrupt routine.
INTERRUPT_HANDLER_TRAP (TRAP_IRQHandler)
TRAP interrupt routine.
void main (void)
Main program.
static void UART_Config (void)
UART1 and UART3 Configuration for interrupt communication.
Variables
uint8_t NbrOfDataToRead1 = RxBufferSize1
uint8_t NbrOfDataToRead2 = RxBufferSize2
uint8_t NbrOfDataToTransfer1 = TxBufferSize1
uint8_t NbrOfDataToTransfer2 = TxBufferSize2
uint8_t RxBuffer1 []
uint8_t RxBuffer1 [RxBufferSize1]
uint8_t RxBuffer2 [RxBufferSize2]
uint8_t RxBuffer2 []
__IO uint8_t RxCounter1 = 0x00
__IO uint8_t RxCounter2 = 0x00
__IO TestStatus TransferStatus1 = FAILED
__IO TestStatus TransferStatus2 = FAILED
uint8_t TxBuffer1 [] = "UART1 Interrupt Example: UART1 -> UART3 using Interrupt"
uint8_t TxBuffer1 []
uint8_t TxBuffer2 []
uint8_t TxBuffer2 [] = "UART1 Interrupt Example: UART3 -> UART1 using Interrupt"
__IO uint8_t TxCounter1 = 0x00
__IO uint8_t TxCounter2 = 0x00
Enumeration Type Documentation
enum TestStatus
Enumerator:
FAILED
PASSED
FAILED
PASSED
FAILED
PASSED
FAILED
PASSED
FAILED
PASSED
FAILED
PASSED
FAILED
PASSED
FAILED
PASSED
FAILED
PASSED
FAILED
PASSED
Definition at line 37 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
Function Documentation
TestStatus Buffercmp (uint8_t * pBuffer1, uint8_t * pBuffer2, uint16_t BufferLength)
Compares two buffers.
Parameters:
[in] pBuffer1 First buffer to be compared.
[in] pBuffer2 Second buffer to be compared.
[in] BufferLength Buffer's length
Return values:
TestStatus Status of buffer comparison
PASSED: pBuffer1 identical to pBuffer2
FAILED: pBuffer1 differs from pBuffer2
Required preconditions:
None
static void CLK_Config (void) [static]
Configure system clock to run at 16Mhz.
Parameters:
None
Return values:
None
void Delay (uint16_t nCount)
Delay.
Inserts a delay time.
Parameters:
nCount
Return values:
None
Parameters:
nCount,: specifies the delay time length.
Return values:
None
Parameters:
nCount
Return values:
None Delay.
Parameters:
nCount the value for looping.
Return values:
None Delay.
Parameters:
nCount,: specifies the delay time length.
Return values:
None
Definition at line 297 of file STM8S_StdPeriph_Examples/AWU/AWU_ActiveHaltMode/main.c.
Referenced by INTERRUPT_HANDLER(), and main().
uint8_t GetVar_NbrOfDataToRead1 (void)
Returns NbrOfDataToRead1 value.
Parameters:
None
Return values:
Rx Buffer Size1
uint8_t: NbrOfDataToRead1
Required preconditions:
None
Definition at line 304 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
References NbrOfDataToRead1.
uint8_t GetVar_NbrOfDataToRead2 (void)
Returns NbrOfDataToRead2 value.
Parameters:
None
Return values:
Rx Buffer Size2
uint8_t: NbrOfDataToRead2
Required preconditions:
None
Definition at line 316 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
References NbrOfDataToRead2.
uint8_t GetVar_NbrOfDataToTransfer1 (void)
Returns NbrOfDataToTransfer1 value.
Parameters:
None
Return values:
Tx Buffer Size1
uint8_t: NbrOfDataToTransfer1
Required preconditions:
None
Definition at line 280 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
References NbrOfDataToTransfer1.
Referenced by main().
uint8_t GetVar_NbrOfDataToTransfer2 (void)
Returns NbrOfDataToTransfer2 value.
Parameters:
None
Return values:
Tx Buffer Size2
uint8_t: NbrOfDataToTransfer2
Required preconditions:
None
Definition at line 292 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
References NbrOfDataToTransfer2.
Referenced by main().
uint8_t GetVar_RxCounter1 (void)
Returns RxCounter1 value.
Parameters:
None
Return values:
Receive counter index1
uint8_t: RxCounter1
Required preconditions:
None
Definition at line 208 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
References RxCounter1.
Referenced by main().
uint8_t GetVar_RxCounter2 (void)
Returns RxCounter2 value.
Parameters:
None
Return values:
Receive counter index2
uint8_t: RxCounter2
Required preconditions:
None
Definition at line 220 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
References RxCounter2.
Referenced by main().
uint8_t GetVar_TxCounter1 (void)
Returns TxCounter1 value.
Parameters:
None
Return values:
Transmit counter index1
uint8_t: TxCounter1
Required preconditions:
None
Definition at line 184 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
References TxCounter1.
uint8_t GetVar_TxCounter2 (void)
Returns TxCounter2 value.
Parameters:
None
Return values:
Transmit counter index2
uint8_t: TxCounter2
Required preconditions:
None
Definition at line 196 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
References TxCounter2.
uint8_t IncrementVar_RxCounter1 (void)
Increments RxCounter1 variable and return its value.
Parameters:
None
Return values:
Receive counter index1++
uint8_t: RxCounter1++
Required preconditions:
None
Definition at line 256 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
References RxCounter1.
uint8_t IncrementVar_RxCounter2 (void)
Increments RxCounter2 variable and return its value.
Parameters:
None
Return values:
Receive counter index2++
uint8_t: RxCounter2++
Required preconditions:
None
Definition at line 268 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
References RxCounter2.
uint8_t IncrementVar_TxCounter1 (void)
Increments TxCounter1 variable and return its value.
Parameters:
None
Return values:
Transmit counter index1++
uint8_t: TxCounter1++
Required preconditions:
None
Definition at line 232 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
References TxCounter1.
uint8_t IncrementVar_TxCounter2 (void)
Increments TxCounter2 variable and return its value.
Parameters:
None
Return values:
Transmit counter index2++
uint8_t: TxCounter2++
Required preconditions:
None
Definition at line 244 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
References TxCounter2.
INTERRUPT_HANDLER (TLI_IRQHandler , 0)
Top Level Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 94 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/stm8s_it.c.
INTERRUPT_HANDLER (AWU_IRQHandler , 1)
Auto Wake Up Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 107 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/stm8s_it.c.
INTERRUPT_HANDLER (CLK_IRQHandler , 2)
Clock Controller Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 120 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTA_IRQHandler , 3)
External Interrupt PORTA Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 133 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTB_IRQHandler , 4)
External Interrupt PORTB Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 145 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTC_IRQHandler , 5)
External Interrupt PORTC Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 158 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTD_IRQHandler , 6)
External Interrupt PORTD Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 171 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTE_IRQHandler , 7)
External Interrupt PORTE Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 184 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/stm8s_it.c.
INTERRUPT_HANDLER (SPI_IRQHandler , 10)
SPI Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 239 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/stm8s_it.c.
INTERRUPT_HANDLER (TIM1_UPD_OVF_TRG_BRK_IRQHandler , 11)
Timer1 Update/Overflow/Trigger/Break Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 252 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/stm8s_it.c.
INTERRUPT_HANDLER (TIM1_CAP_COM_IRQHandler , 12)
Timer1 Capture/Compare Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 265 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/stm8s_it.c.
INTERRUPT_HANDLER (TIM2_UPD_OVF_BRK_IRQHandler , 13)
Timer2 Update/Overflow/Break Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 305 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/stm8s_it.c.
INTERRUPT_HANDLER (TIM2_CAP_COM_IRQHandler , 14)
Timer2 Capture/Compare Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 318 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/stm8s_it.c.
INTERRUPT_HANDLER (I2C_IRQHandler , 19)
I2C Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 400 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/stm8s_it.c.
INTERRUPT_HANDLER (ADC1_IRQHandler , 22)
ADC1 interrupt routine.
Parameters:
None
Return values:
None
Definition at line 492 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/stm8s_it.c.
INTERRUPT_HANDLER (TIM4_UPD_OVF_IRQHandler , 23)
Timer4 Update/Overflow Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 520 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/stm8s_it.c.
INTERRUPT_HANDLER (EEPROM_EEC_IRQHandler , 24)
Eeprom EEC Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 534 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/stm8s_it.c.
INTERRUPT_HANDLER_TRAP (TRAP_IRQHandler)
TRAP interrupt routine.
Parameters:
None
Return values:
None
Definition at line 80 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/stm8s_it.c.
void main (void)
Main program.
Parameters:
None
Return values:
None
Definition at line 65 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
References Buffercmp(), CLK_Config(), ENABLE, GetVar_NbrOfDataToTransfer1(), GetVar_NbrOfDataToTransfer2(), GetVar_RxCounter1(), GetVar_RxCounter2(), RxBuffer1, RxBuffer2, RxBufferSize1, RxBufferSize2, TransferStatus1, TransferStatus2, TxBuffer1, TxBuffer2, UART1_IT_RXNE_OR, UART1_ITConfig(), UART3_IT_TXE, UART3_ITConfig(), and UART_Config().
static void UART_Config (void) [static]
UART1 and UART3 Configuration for interrupt communication.
Parameters:
None
Return values:
None
Definition at line 118 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
References ENABLE, enableInterrupts, UART1_DeInit(), UART1_Init(), UART1_IT_TXE, UART1_ITConfig(), UART1_MODE_TXRX_ENABLE, UART1_PARITY_NO, UART1_STOPBITS_1, UART1_SYNCMODE_CLOCK_DISABLE, UART1_WORDLENGTH_8D, UART3_DeInit(), UART3_Init(), UART3_IT_RXNE_OR, UART3_ITConfig(), UART3_MODE_TXRX_ENABLE, UART3_PARITY_NO, UART3_STOPBITS_1, and UART3_WORDLENGTH_8D.
Referenced by main().
Variable Documentation
uint8_t NbrOfDataToRead1 = RxBufferSize1
Definition at line 49 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
uint8_t NbrOfDataToRead2 = RxBufferSize2
Definition at line 50 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
uint8_t NbrOfDataToTransfer1 = TxBufferSize1
Definition at line 47 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
Referenced by GetVar_NbrOfDataToTransfer1().
uint8_t NbrOfDataToTransfer2 = TxBufferSize2
Definition at line 48 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
Referenced by GetVar_NbrOfDataToTransfer2().
uint8_t RxBuffer1[]
Definition at line 51 of file STM8S_StdPeriph_Examples/SPI/SPI_FullDuplexUART1/main.c.
Referenced by main().
uint8_t RxBuffer1[RxBufferSize1]
Definition at line 41 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
uint8_t RxBuffer2[RxBufferSize2]
Definition at line 42 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
uint8_t RxBuffer2[]
Definition at line 52 of file STM8S_StdPeriph_Examples/SPI/SPI_FullDuplexUART1/main.c.
Referenced by main().
__IO uint8_t RxCounter1 = 0x00
Definition at line 45 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
__IO uint8_t RxCounter2 = 0x00
Definition at line 46 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
__IO TestStatus TransferStatus1 = FAILED
Definition at line 51 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
__IO TestStatus TransferStatus2 = FAILED
Definition at line 52 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
uint8_t TxBuffer1[] = "UART1 Interrupt Example: UART1 -> UART3 using Interrupt"
Definition at line 39 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
uint8_t TxBuffer1[]
Definition at line 49 of file STM8S_StdPeriph_Examples/SPI/SPI_FullDuplexUART1/main.c.
Referenced by main().
uint8_t TxBuffer2[]
Definition at line 50 of file STM8S_StdPeriph_Examples/SPI/SPI_FullDuplexUART1/main.c.
Referenced by main().
uint8_t TxBuffer2[] = "UART1 Interrupt Example: UART3 -> UART1 using Interrupt"
Definition at line 40 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
__IO uint8_t TxCounter1 = 0x00
Definition at line 43 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
__IO uint8_t TxCounter2 = 0x00
Definition at line 44 of file STM8S_StdPeriph_Examples/UART1/UART1_Interrupt/main.c.
For complete documentation on STM8 8-bit Microcontrollers platform visit www.st.com