STM8S/A Standard Peripherals Firmware Library: WWDG_Example
WWDG_Example
Defines
#define COUNTER_INIT 104
#define WINDOW_VALUE 97
Functions
void Delay (uint16_t nCount)
Inserts a delay time.
static void GPIO_Config (void)
Configures the Leds and the Buttons IO.
INTERRUPT_HANDLER (TLI_IRQHandler, 0)
Top Level Interrupt routine.
INTERRUPT_HANDLER (AWU_IRQHandler, 1)
Auto Wake Up Interrupt routine.
INTERRUPT_HANDLER (CLK_IRQHandler, 2)
Clock Controller Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTA_IRQHandler, 3)
External Interrupt PORTA Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTB_IRQHandler, 4)
External Interrupt PORTB Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTC_IRQHandler, 5)
External Interrupt PORTC Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTD_IRQHandler, 6)
External Interrupt PORTD Interrupt routine.
INTERRUPT_HANDLER (EXTI_PORTE_IRQHandler, 7)
External Interrupt PORTE Interrupt routine.
INTERRUPT_HANDLER (SPI_IRQHandler, 10)
SPI Interrupt routine.
INTERRUPT_HANDLER (TIM1_UPD_OVF_TRG_BRK_IRQHandler, 11)
Timer1 Update/Overflow/Trigger/Break Interrupt routine.
INTERRUPT_HANDLER (TIM1_CAP_COM_IRQHandler, 12)
Timer1 Capture/Compare Interrupt routine.
INTERRUPT_HANDLER (TIM2_UPD_OVF_BRK_IRQHandler, 13)
Timer2 Update/Overflow/Break Interrupt routine.
INTERRUPT_HANDLER (TIM2_CAP_COM_IRQHandler, 14)
Timer2 Capture/Compare Interrupt routine.
INTERRUPT_HANDLER (I2C_IRQHandler, 19)
I2C Interrupt routine.
INTERRUPT_HANDLER (ADC1_IRQHandler, 22)
ADC1 interrupt routine.
INTERRUPT_HANDLER (TIM4_UPD_OVF_IRQHandler, 23)
Timer4 Update/Overflow Interrupt routine.
INTERRUPT_HANDLER (EEPROM_EEC_IRQHandler, 24)
Eeprom EEC Interrupt routine.
INTERRUPT_HANDLER_TRAP (TRAP_IRQHandler)
TRAP interrupt routine.
void main (void)
Main program.
static void WWDG_Config (void)
Configures the WWDG to generate a Reset if the WWDG is not refreshed during the correct window.
Variables
__IO FunctionalState AllowedRefresh
__IO FunctionalState AllowedRefresh = ENABLE
uint8_t Index
__IO FunctionalState NonAlowedRefresh
__IO FunctionalState NonAlowedRefresh = DISABLE
Define Documentation
#define COUNTER_INIT 104
Definition at line 39 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/main.c.
Referenced by main(), and WWDG_Config().
#define WINDOW_VALUE 97
Definition at line 38 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/main.c.
Referenced by main(), and WWDG_Config().
Function Documentation
void Delay (uint16_t nCount)
Inserts a delay time.
Delay.
Parameters:
nCount,: specifies the delay time length.
Return values:
None
Definition at line 297 of file STM8S_StdPeriph_Examples/AWU/AWU_ActiveHaltMode/main.c.
static void GPIO_Config (void) [static]
Configures the Leds and the Buttons IO.
Parameters:
None
Return values:
None
INTERRUPT_HANDLER (TLI_IRQHandler , 0)
Top Level Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 77 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/stm8s_it.c.
INTERRUPT_HANDLER (AWU_IRQHandler , 1)
Auto Wake Up Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 89 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/stm8s_it.c.
INTERRUPT_HANDLER (CLK_IRQHandler , 2)
Clock Controller Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 101 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTA_IRQHandler , 3)
External Interrupt PORTA Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 113 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTB_IRQHandler , 4)
External Interrupt PORTB Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 125 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/stm8s_it.c.
References ENABLE, LED2, NonAlowedRefresh, and STM_EVAL_LEDOff().
INTERRUPT_HANDLER (EXTI_PORTC_IRQHandler , 5)
External Interrupt PORTC Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 138 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/stm8s_it.c.
References AllowedRefresh, DISABLE, LED2, and STM_EVAL_LEDOff().
INTERRUPT_HANDLER (EXTI_PORTD_IRQHandler , 6)
External Interrupt PORTD Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 151 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/stm8s_it.c.
INTERRUPT_HANDLER (EXTI_PORTE_IRQHandler , 7)
External Interrupt PORTE Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 163 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/stm8s_it.c.
INTERRUPT_HANDLER (SPI_IRQHandler , 10)
SPI Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 214 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/stm8s_it.c.
INTERRUPT_HANDLER (TIM1_UPD_OVF_TRG_BRK_IRQHandler , 11)
Timer1 Update/Overflow/Trigger/Break Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 226 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/stm8s_it.c.
INTERRUPT_HANDLER (TIM1_CAP_COM_IRQHandler , 12)
Timer1 Capture/Compare Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 238 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/stm8s_it.c.
INTERRUPT_HANDLER (TIM2_UPD_OVF_BRK_IRQHandler , 13)
Timer2 Update/Overflow/Break Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 275 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/stm8s_it.c.
INTERRUPT_HANDLER (TIM2_CAP_COM_IRQHandler , 14)
Timer2 Capture/Compare Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 287 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/stm8s_it.c.
INTERRUPT_HANDLER (I2C_IRQHandler , 19)
I2C Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 354 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/stm8s_it.c.
INTERRUPT_HANDLER (ADC1_IRQHandler , 22)
ADC1 interrupt routine.
Parameters:
None
Return values:
None
Definition at line 432 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/stm8s_it.c.
INTERRUPT_HANDLER (TIM4_UPD_OVF_IRQHandler , 23)
Timer4 Update/Overflow Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 459 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/stm8s_it.c.
INTERRUPT_HANDLER (EEPROM_EEC_IRQHandler , 24)
Eeprom EEC Interrupt routine.
Parameters:
None
Return values:
None
Definition at line 472 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/stm8s_it.c.
INTERRUPT_HANDLER_TRAP (TRAP_IRQHandler)
TRAP interrupt routine.
Parameters:
None
Return values:
None
Definition at line 66 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/stm8s_it.c.
void main (void)
Main program.
Parameters:
None
Return values:
None
Definition at line 58 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/main.c.
References AllowedRefresh, COUNTER_INIT, Delay(), DISABLE, GPIO_Config(), Index, LED1, LED2, NonAlowedRefresh, RESET, RST_ClearFlag(), RST_FLAG_WWDGF, RST_GetFlagStatus(), STM_EVAL_LEDToggle(), WINDOW_VALUE, WWDG_Config(), WWDG_GetCounter(), and WWDG_SetCounter().
static void WWDG_Config (void) [static]
Configures the WWDG to generate a Reset if the WWDG is not refreshed during the correct window.
Parameters:
None
Return values:
None
Definition at line 129 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/main.c.
References COUNTER_INIT, WINDOW_VALUE, and WWDG_Init().
Referenced by main().
Variable Documentation
__IO FunctionalState AllowedRefresh
Definition at line 44 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/main.c.
Referenced by INTERRUPT_HANDLER(), and main().
__IO FunctionalState AllowedRefresh = ENABLE
Definition at line 44 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/main.c.
Referenced by INTERRUPT_HANDLER(), and main().
uint8_t Index
Definition at line 45 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/main.c.
Referenced by main().
__IO FunctionalState NonAlowedRefresh
Definition at line 43 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/main.c.
Referenced by INTERRUPT_HANDLER(), and main().
__IO FunctionalState NonAlowedRefresh = DISABLE
Definition at line 43 of file STM8S_StdPeriph_Examples/WWDG/WWDG_Example/main.c.
Referenced by INTERRUPT_HANDLER(), and main().
For complete documentation on STM8 8-bit Microcontrollers platform visit www.st.com