STM8S/A Standard Peripherals Firmware Library: STM8S_EVAL_LCD_Private_Function_Prototypes
STM8S_EVAL_LCD_Private_Function_Prototypes
STM8S_EVAL_LCD
Functions
static void delay (__IO uint32_t nCount)
The delay function implemented in this driver is not a precise one, however it allows the insertion of 1ms delay when Fcpu is 16Mhz if the passed parameter is 0x4000.
static void LCD_DisplayCGRAM0 (uint8_t address, uint8_t *ptrTable)
Display CGRAM on even address.
static void LCD_DisplayCGRAM1 (uint8_t address, uint8_t *ptrTable)
Display CGRAM on odd address.
static void LCD_SPISendByte (uint8_t DataToSend)
Send a byte to LCD through the SPI peripheral.
Function Documentation
static void delay (__IO uint32_t nCount) [static]
The delay function implemented in this driver is not a precise one, however it allows the insertion of 1ms delay when Fcpu is 16Mhz if the passed parameter is 0x4000.
Inserts a delay time.
Any change in system clock frequency will impact this delay duration.
User is given the possibility to develop a customized and accurate delay function by the mean of timers for example. Uncommenting " #define USE_Delay" line in the stm8s_eval_lcd.h file will allow the consideration of the new function by this driver.
The delay function implemented in this driver is not a precise one, however it allows the insertion of 1ms delay when Fcpu is 16Mhz if the passed parameter is 0x4000. Any change in system clock frequency will impact this delay duration.
User is given the possibility to develop a customized and accurate delay function by the mean of timers for example. Uncommenting " #define USE_Delay" line in the stm8s_eval_lcd.h file will allow the consideration of the new function by this driver.
Parameters:
nCount,: specifies the _delay_ time length.
Return values:
None
Definition at line 431 of file stm8s_eval_lcd.c.
static void LCD_DisplayCGRAM0 (uint8_t address, uint8_t * ptrTable) [static]
Display CGRAM on even address.
Parameters:
address : Display address
ptrTable : Pointer a the CGRAM table to be displayed
Return values:
None
Definition at line 367 of file stm8s_eval_lcd.c.
References COMMAND_TYPE, DATA_TYPE, and LCD_SendByte().
Referenced by LCD_DisplayLogo().
static void LCD_DisplayCGRAM1 (uint8_t address, uint8_t * ptrTable) [static]
Display CGRAM on odd address.
Parameters:
address : Display address
ptrTable : Pointer a the CGRAM table to be displayed
Return values:
None
Definition at line 394 of file stm8s_eval_lcd.c.
References COMMAND_TYPE, DATA_TYPE, and LCD_SendByte().
Referenced by LCD_DisplayLogo().
static void LCD_SPISendByte (uint8_t DataToSend) [static]
Send a byte to LCD through the SPI peripheral.
Parameters:
DataToSend : Data to be sent
Return values:
None
Definition at line 349 of file stm8s_eval_lcd.c.
References LCD_SPI, and SPI_SR_TXE.
Referenced by LCD_SendByte().
For complete documentation on STM8 8-bit Microcontrollers platform visit www.st.com