STM8S/A Standard Peripherals Firmware Library: AWU_ActiveHaltMode
AWU_ActiveHaltMode
Functions
void AWU_Config (void)
Configure the AWU time base to 12s.
static void CLK_Config (void)
Configure system clock to run at 16Mhz.
static void GPIO_Config (void)
Configure GPIO for LEDs and buttons available on the evaluation board.
static void LCD_Config (void)
Configure the LCD available on the evaluation board.
void main (void)
Example main entry point.
Variables
bool ButtonPressed = FALSE
Function Documentation
void AWU_Config (void)
Configure the AWU time base to 12s.
Parameters:
None
Return values:
None
Definition at line 159 of file STM8S_StdPeriph_Examples/AWU/AWU_ActiveHaltMode/main.c.
References AWU_Init(), AWU_LSICalibrationConfig(), AWU_TIMEBASE_12S, and LSIMeasurment().
Referenced by main().
static void CLK_Config (void) [static]
Configure system clock to run at 16Mhz.
Parameters:
None
Return values:
None
Definition at line 147 of file STM8S_StdPeriph_Examples/AWU/AWU_ActiveHaltMode/main.c.
References CLK_HSIPrescalerConfig(), and CLK_PRESCALER_HSIDIV1.
Referenced by main().
static void GPIO_Config (void) [static]
Configure GPIO for LEDs and buttons available on the evaluation board.
Parameters:
None
Return values:
None
Definition at line 174 of file STM8S_StdPeriph_Examples/AWU/AWU_ActiveHaltMode/main.c.
References BUTTON_KEY, BUTTON_MODE_EXTI, LED1, LED2, LED3, LED4, STM_EVAL_LEDInit(), and STM_EVAL_PBInit().
static void LCD_Config (void) [static]
Configure the LCD available on the evaluation board.
Parameters:
None
Return values:
None
Definition at line 191 of file STM8S_StdPeriph_Examples/AWU/AWU_ActiveHaltMode/main.c.
References LCD_Clear(), LCD_LINE1, LCD_LINE2, LCD_Print(), LCD_SetCursorPos(), and STM8S_EVAL_LCD_Init().
Referenced by main().
void main (void)
Example main entry point.
Parameters:
None
Return values:
None
Definition at line 58 of file STM8S_StdPeriph_Examples/AWU/AWU_ActiveHaltMode/main.c.
References AWU_Config(), ButtonPressed, CLK_Config(), Delay(), enableInterrupts, FALSE, GPIO_Config(), halt, i, LCD_Clear(), LCD_Config(), LCD_LINE1, LCD_LINE2, LCD_Print(), LCD_SetCursorPos(), LED1, LED2, LED3, LED4, STM_EVAL_LEDOff(), STM_EVAL_LEDToggle(), and TRUE.
Variable Documentation
bool ButtonPressed = FALSE
Definition at line 43 of file STM8S_StdPeriph_Examples/AWU/AWU_ActiveHaltMode/main.c.
Referenced by INTERRUPT_HANDLER(), and main().
For complete documentation on STM8 8-bit Microcontrollers platform visit www.st.com